FROM golang:1.23-alpine AS builder
WORKDIR /app

RUN apk add --no-cache git ca-certificates

ENV GONOSUMDB=*
ENV GOFLAGS=-mod=mod
ENV CGO_ENABLED=0
ENV GOPATH=/go

# cache dependencies separately
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -ldflags="-w -s" -o core-server ./cmd/core

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/core-server .
EXPOSE 9000
CMD ["./core-server"]
