FROM golang:1.23-alpine AS builder
WORKDIR /app

RUN apk add --no-cache git ca-certificates

ENV GONOSUMDB=*
ENV GOFLAGS=-mod=mod
ENV CGO_ENABLED=0
ENV GOPATH=/go

COPY . .

RUN go mod tidy && go build -ldflags="-w -s" -o auth-server ./cmd/auth

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/auth-server .
EXPOSE 9001
CMD ["./auth-server"]
