FROM golang:1.23-alpine AS builder
WORKDIR /app

RUN apk add --no-cache git

ENV GONOSUMCHECK=*
ENV GOFLAGS=-mod=mod
ENV GONOSUMDB=*
ENV GOFLAGS=-mod=mod

COPY go.mod ./
COPY . .

RUN go mod tidy && go build -o auth-server ./cmd/auth

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/auth-server .
EXPOSE 9001
CMD ["./auth-server"]
