FROM golang:1.23-alpine AS builder
WORKDIR /app

RUN apk add --no-cache git

ENV GONOSUMCHECK=*
ENV GOFLAGS=-mod=mod
ENV GONOSUMDB=*

COPY go.mod ./
COPY . .

RUN go mod tidy && go build -o core-server ./cmd/core

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/core-server .
EXPOSE 9000
CMD ["./core-server"]
